version: '3.9'
services:
  db:
    image: sakiladb/postgres:latest
    container_name: sakila-db
    environment:
      POSTGRES_DB: sakila
      POSTGRES_USER: sakila
      POSTGRES_PASSWORD: p_ssW0rd
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: sakila-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sakila-db:5432/sakila
      SPRING_DATASOURCE_USERNAME: sakila
      SPRING_DATASOURCE_PASSWORD: p_ssW0rd
    ports:
      - "8080:8080"